name: API-Build

on:
  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - name: Form API
        run: |
          username=${{  github.event.inputs.name  }}
          echo "The current user is: $username"
  
