name: Composite

on: 
  push:
    branches:
      "**"

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use Composite Action
        uses: Dipanshuonline/GithubAction/.github/workflows/action.yml@v1
        with:
          myInput: 'Hello, world!'
