name: Selenium and Jmeter

on: 
  push:
    branches:
      "**"

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Collect build data
        if: always()
        run: |
          username=$(ls -R /github/workspace)
          echo "The current user is: $username"
    #  - name: run Selenium
    #    run: mvn test
      - name: Apache JMeter
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: /home/runner/work/GithubAction/GithubAction/Jmeter/AutopacingJmeter.jmx
          outputReportsFolder: Jmeter/
      - name: List Workspace Contents
        run: ls -R /github/workspace
