name: Selenium and Jmeter

on: 
  push:
    branches:
      "**"

jobs:
  run-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Collect build data
        if: always()
        run: |
          username=$(whoami)
          echo "The current user is: $username"
          username=$(pwd)
          echo "The current user is: $username"
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd Jmeter
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          chmod -R 777 Jmeter/
          cd Jmeter
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          cd Resources
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          chmod -R 777 Resources/
          cd Resources
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
      - name: Setup Chrome
  # You may pin to the exact commit or the version.
  # uses: browser-actions/setup-chrome@803ef6dfb4fdf22089c9563225d95e4a515820a0
        uses: browser-actions/setup-chrome@v1.2.3
        with:
    # The Google Chrome/Chromium version to install and use.
          chrome-version: default
      - name: run Selenium
        run: mvn test
      - name: Apache JMeter
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
           testFilePath: Jmeter/AutopacingJmeter.jmx
           outputReportsFolder: Jmeter/
      
