name: scheduled

on:
  push:
  schedule:
  #- cron: "0 */8 * * *"
  - cron: "*/2 * * * *"
  
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Collect build data
        if: always()
        run: |
          username=$(whoami)
          echo "The current user is: $username"
          username=$(pwd)
          echo "The current user is: $username"
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd Jmeter
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          chmod 777 Jmeter
          chmod -R 777 Jmeter/
          cd Jmeter
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          cd Resources
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          chmod -R 777 Resources/
          cd Resources
          username=$(ls -lrt)
          echo "The current user is: $username"
          cd ..
          username=$(ls -lrt)
          echo "The current user is: $username"
      - name: run Selenium
        run: mvn test
      
